apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocketbase.fullname" . }}-admin-secret
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc | quote }}
  password: {{ randAlphaNum 10 | b64enc | quote }}