apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pocketbase.fullname" . }}-pvc
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"

spec:
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- if .Values.storage.volumeName }}
  volumeName: {{ .Values.storage.volumeName | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessMode | quote  }}
  resources:
    requests:
      storage: {{ .Values.storage.request | quote  }}