nameOverride: ""
fullnameOverride: ""

ingress:
  className: ""
  annotations: {}
  directus:
    host: directus.example.com
  code:
    host: code.example.com

storage: 
  directus:
    storageClassName: ""
    volumeName: ""
    accessMode: "ReadWriteOnce"
    request: "50Gi"
  code:
    storageClassName: ""
    volumeName: ""
    accessMode: "ReadWriteOnce"
    request: "10Gi"

admin:
  username: example@test.com
