apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}-admin-secret
  labels:
    {{- include "directus.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc | quote }}
  password: {{ randAlphaNum 10 | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code.fullname" . }}-admin-secret
  labels:
    {{- include "code.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    
type: Opaque
data:
  password: {{ randAlphaNum 10 | b64enc | quote }}
  sudoPassword: {{ randAlphaNum 10 | b64enc | quote }}