apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "directus.fullname" . }}-deploy
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: directus
        image: directus/directus
        ports:
          - containerPort: 8055
        env:
          - name: PUBLIC_URL
            value: "https://{{ .Values.ingress.directus.host }}"
          - name: KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.serverSecretName" . }}
                key: key
                optional: false
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.serverSecretName" . }}
                key: secret
                optional: false
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.adminSecretName" . }}
                key: username
                optional: false
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.adminSecretName" . }}
                key: password
                optional: false
          - name: DB_CLIENT
            value: "sqlite3"
          - name: DB_FILENAME
            value: "/directus/database/data.db"
          - name: WEBSOCKETS_ENABLED
            value: "true"
          - name: LOG_LEVEL
            value: "info"
          - name: EXTENSIONS_AUTO_RELOAD
            value: "true"
        volumeMounts:
          - name: directus-data
            mountPath: /directus/database
            subPath: database
          - name: directus-data
            mountPath: /directus/uploads
            subPath: uploads
          - name: directus-data
            mountPath: /directus/extensions
            subPath: extensions
        resources:
          {{- with .Values.resources.directus }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
        - name: directus-data
          persistentVolumeClaim:
            claimName: {{ include "directus.pvcName" . }}