apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "directus.fullname" . }}-deploy
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: directus
        image: directus/directus
        ports:
          - containerPort: 8055
        env:
          - name: PUBLIC_URL
            value: "https://{{ .Values.ingress.directus.host }}"
          - name: KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.serverSecretName" . }}
                key: key
                optional: false
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.serverSecretName" . }}
                key: secret
                optional: false
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.adminSecretName" . }}
                key: username
                optional: false
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "directus.adminSecretName" . }}
                key: password
                optional: false
          - name: DB_CLIENT
            value: "sqlite3"
          - name: DB_FILENAME
            value: "/directus/database/data.db"
          - name: WEBSOCKETS_ENABLED
            value: "true"
          - name: LOG_LEVEL
            value: "info"
          - name: EXTENSIONS_AUTO_RELOAD
            value: "true"
        volumeMounts:
          - name: directus-data
            mountPath: /directus/database
            subPath: database
          - name: directus-data
            mountPath: /directus/uploads
            subPath: uploads
          - name: directus-data
            mountPath: /directus/extensions
            subPath: extensions
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
      volumes:
        - name: directus-data
          persistentVolumeClaim:
            claimName: {{ include "directus.pvcName" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code.fullname" . }}-deploy
  labels:
    {{- include "code.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "code.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "code.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: code-server
        image: linuxserver/code-server
        ports:
          - containerPort: 8443
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Asia/Seoul"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "code.adminSecretName" . }}
                key: password
                optional: false
          - name: SUDO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "code.adminSecretName" . }}
                key: sudoPassword
                optional: false
        volumeMounts:
          - name: directus-data
            mountPath: /config/directus
            subPath: extensions
          - name: data
            mountPath: /config/workspace
            subPath: workspace
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      volumes:
        - name: directus-data
          persistentVolumeClaim:
            claimName: {{ include "directus.pvcName" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "code.pvcName" . }}