apiVersion: v1
kind: Service
metadata:
  name: {{ include "directus.fullname" . }}-service
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8055
      name: web
      targetPort: 8055
  type: ClusterIP
  selector:
    {{- include "directus.selectorLabels" . | nindent 4 }}