apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}-server-secret
  labels:
    {{- include "directus.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"

type: Opaque
data:
  key: {{ uuidv4 | b64enc | quote }}
  secret: {{ randAlphaNum 32 | b64enc | quote }}